rankit/__init__.py
from flask import Flask
import logging, sys


app = Flask(__name__)
logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
app.config.from_object('config.ProductionConfig')


from rankit.home.views import home_blueprint
from rankit.build.views import build_blueprint
from rankit.explore.views import explore_blueprint
from rankit.datasets.views import datasets_blueprint

app.register_blueprint(home_blueprint)
app.register_blueprint(build_blueprint)
app.register_blueprint(explore_blueprint)
app.register_blueprint(datasets_blueprint)

rankit/datasets/views.py
from flask import Blueprint, render_template


datasets_blueprint = Blueprint(
    'datasets', __name__,
    static_folder='static',
    template_folder='templates'
)


@datasets_blueprint.route('/dataset')
def datasets():
    return render_template('full_datasets.html')

rankit/explore/views.py
from flask import Blueprint, request, render_template
from rankit.build.utils import getRanking
from  rankit.datasets.utils import getDataset

import json, re

explore_blueprint = Blueprint(
    'explore', __name__,
    template_folder='templates'
)


@explore_blueprint.route('/explore/<dataset_name>/')
def explore(dataset_name):

    data = json.dumps(getDataset(dataset_name))

    return render_template('explore.html', weights=None, data=data, dataset_name=dataset_name, list=None)


@explore_blueprint.route('/explore/<dataset_name>/<pairs>')
def exploreJson(dataset_name, pairs):
    primaryKeyPairs = []
    parsed_pairs = re.findall("\d+=([\w\s'-:!\.,()]*[\>]{1}[\w\s'-:!\.,()]*)&", pairs)

    # for pair in parsed_pairs:
    #     high, low = pair.split('>')
    #     primaryKeyPairs.append({'high': high, 'low' : low})
    list = []


    for pair in parsed_pairs:
        high, low = pair.split('>')
        if (high not in list): list.append(high)
        if (low not in list): list.append(low)
        primaryKeyPairs.append({'high': high, 'low' : low})

    data, weights, confidence = getRanking(dataset_name, primaryKeyPairs)

    return render_template('explore.html', weights=weights, data=data, dataset_name=dataset_name, list=list)

rankit/home/views.py
from flask import render_template, Blueprint, request

home_blueprint = Blueprint(
    'home', __name__,
    template_folder='templates'
)

@home_blueprint.route('/')
def index():
    return render_template('index.html')

@home_blueprint.route('/about')
def about():
    return render_template('about.html')

rankit/templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
  <meta charset="UTF-8">
  <script type="text/javascript" src="{{ url_for('static', filename = 'js/lib/modernizr.custom.js') }}"></script>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='styles/bootstrap-iso.css') }}"/>
  <link rel="icon" href="{{ url_for('static',filename='img/favicon.png') }}">
  <link rel="shortcut icon" href="{{ url_for('static',filename='img/favicon.ico') }}">
</head>

<body>
  <div class="container">
    <div class="bootstrap-iso">
      <nav id='nav_bar' class="navbar navbar-default navbar-fixed-top sticky" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse">
            <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
          </button> <a style="font-weight:bold" class="navbar-brand" href={{ url_for('home.index') }}>RANKIT</a>
        </div>
        <div>
          <ul class="nav navbar-nav navbar-right" id="main-menu">
            <li>
              <a href={{ url_for('datasets.datasets') }} >Start RANKIT</a>
            </li>
            <li>
              <a href={{ url_for('home.about') }}>About</a>
            </li>
          </ul>
        </div>
      </nav>
    </div>
    {% block content %}
    {% endblock %}
  </div>
  <div class="footer navbar-fixed-bottom"> © 2018 Worcester Polytechnic Institute All Rights Reserved. </div>
</body>

</html>